const shopLocations = [
  {
    id: 1,
    name: "Urban Outfitters",
    category: "Fashion",
    address: "Komuna e Parisit, Tiranë, Albania",
    lat: 41.3203,
    lng: 19.8239,
  },
  {
    id: 2,
    name: "Tech Hub",
    category: "Electronics",
    address: "Rruga e Dibrës, Tiranë, Albania",
    lat: 41.3243,
    lng: 19.8183,
  },
  {
    id: 3,
    name: "Coffee Corner",
    category: "Cafe",
    address: "Blloku, Tiranë, Albania",
    lat: 41.3193,
    lng: 19.8162,
  },
  {
    id: 4,
    name: "Nike Store",
    category: "Fashion",
    address: "Toptani Shopping Center, Tiranë, Albania",
    lat: 41.3283,
    lng: 19.8195,
  },
  {
    id: 5,
    name: "Guess",
    category: "Fashion",
    address: "Tirana East Gate (TEG), Tiranë, Albania",
    lat: 41.3123,
    lng: 19.8722,
  },
  {
    id: 6,
    name: "Adidas Store",
    category: "Fashion",
    address: "Rruga Myslym Shyri, Tiranë, Albania",
    lat: 41.3277,
    lng: 19.8156,
  },
  {
    id: 7,
    name: "Zara Basic",
    category: "Fashion",
    address: "Skanderbeg Square, Tiranë, Albania",
    lat: 41.3275,
    lng: 19.8189,
  },
  {
    id: 8,
    name: "Zara TRF",
    category: "Fashion",
    address: "Ring Center Mall, Tiranë, Albania",
    lat: 41.3289,
    lng: 19.8065,
  },
  {
    id: 9,
    name: "H&M Divided",
    category: "Fashion",
    address: "Qendra Tregtare Univers, Tiranë, Albania",
    lat: 41.3256,
    lng: 19.8167,
  },
  {
    id: 10,
    name: "Forever 21",
    category: "Fashion",
    address: "City Park, Tiranë, Albania",
    lat: 41.3728,
    lng: 19.7157,
  },
];

export default shopLocations;
